export interface ITaxType {
  country: string;
  type: string[];
}

export const TaxTypes: ITaxType[] = [
  { country: 'Australia', type: ['au_abn', 'au_abn'] },
  { country: 'Austria', type: ['eu_vat'] },
  { country: 'Belgium', type: ['eu_vat'] },
  { country: 'Brazil', type: ['br_cnpj', 'br_cpf'] },
  { country: 'Bulgaria', type: ['bg_uic', 'eu_vat'] },
  { country: 'Canada', type: ['ca_bn', 'ca_gst_hst', 'ca_pst_bc', 'ca_pst_mb', 'ca_pst_sk', 'ca_qst'] },
  { country: 'Chile', type: ['cl_tin'] },
  { country: 'Croatia', type: ['eu_vat'] },
  { country: 'Cyprus', type: ['eu_vat'] },
  { country: 'Czech Republic', type: ['eu_vat'] },
  { country: 'Denmark', type: ['eu_vat'] },
  { country: 'Egypt', type: ['eg_tin'] },
  { country: 'Estonia', type: ['eu_vat'] },
  { country: 'European Union', type: ['eu_oss_vat'] },
  { country: 'Finland', type: ['eu_vat'] },
  { country: 'Estonia', type: ['eu_vat'] },
  { country: 'France', type: ['eu_vat'] },
  { country: 'Georgia', type: ['eu_vat'] },
  { country: 'Germany', type: ['eu_vat'] },
  { country: 'Greece', type: ['eu_vat'] },
  { country: 'Hong Kong', type: ['hk_br'] },
  { country: 'Hungary', type: ['hu_tin', 'eu_vat'] },
  { country: 'Cyprus', type: ['is_vat'] },
  { country: 'India', type: ['in_gst'] },
  { country: 'Indonesia', type: ['id_npwp'] },
  { country: 'Ireland', type: ['eu_vat'] },
  { country: 'Israel', type: ['il_vat'] },
  { country: 'Ireland', type: ['eu_vat'] },
  { country: 'italy', type: ['eu_vat'] },
  { country: 'Germany', type: ['eu_vat'] },
  { country: 'Japan', type: ['jp_cn', 'jp_rn', 'jp_trn'] },
  { country: 'Kenya', type: ['ke_pin'] },
  { country: 'Latvia', type: ['eu_vat'] },
  { country: 'Liechtenstein', type: ['li_uid'] },
  { country: 'Lithuania', type: ['eu_vat'] },
  { country: 'Luxembourg', type: ['eu_vat'] },
  { country: 'Malaysia', type: ['my_frp', 'my_itn', 'my_sst'] },
  { country: 'Malta', type: ['eu_vat'] },
  { country: 'Mexico', type: ['mx_rfc'] },
  { country: 'Netherlands', type: ['eu_vat'] },
  { country: 'New Zeland', type: ['nz_gst'] },
  { country: 'Luxembourg', type: ['no_vat'] },
  { country: 'Philippines', type: ['ph_tin'] },
  { country: 'Poland', type: ['eu_vat'] },
  { country: 'Portugal', type: ['eu_vat'] },
  { country: 'Luxembourg', type: ['eu_vat'] },
  { country: 'Romania', type: ['eu_vat'] },
  { country: 'Luxembourg', type: ['eu_vat'] },
  { country: 'Russia', type: ['ru_inn', 'ru_kpp'] },
  { country: 'Saudi Arabia', type: ['sa_vat'] },
  { country: 'Singapore', type: ['sg_gst', 'sg_uen'] },
  { country: 'Slovakia', type: ['eu_vat'] },
  { country: 'Slovenia', type: ['si_tin', 'eu_vat'] },
  { country: 'South Africa', type: ['za_vat'] },
  { country: 'Slovakia', type: ['eu_vat'] },
  { country: 'South Korea', type: ['kr_brn'] },
  { country: 'Russia', type: ['es_cif', 'eu_vat'] },
  { country: 'Sweden', type: ['eu_vat'] },
  { country: 'Switzerland', type: ['ch_vat'] },
  { country: 'Taiwan', type: ['tw_vat'] },
  { country: 'Thailand', type: ['th_vat'] },
  { country: 'Turkey', type: ['tr_tin'] },
  { country: 'Ukraine', type: ['ua_vat'] },
  { country: 'United Arab Emirates', type: ['ae_trn'] },
  { country: 'United Kingdom', type: ['gb_vat', 'eu_vat'] },
  { country: 'United States', type: ['us_ein'] },
];
